
server:
  port: 8181


spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3316/event-sourcing?allowPublicKeyRetrieval=True
        username: root
        password: root

    kafka: 
        listener:
            ack-mode: MANUAL_IMMEDIATE
        consumer:
            bootstrap-servers: broker:9092
            group-id: queryConsumer
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer        
            properties:
                spring:
                    json:
                        trusted:
                            packages: '*'
